  - name: Install dependencies
    run: npm install @google-cloud/dialogflow
    working-directory: './personal_genchatbotconnector'

  - name: Deploy Worker
    uses: cloudflare/wrangler-action@v3
    with:
      apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      command: deploy --name genchatbotconnector --compatibility-date "2025-09-19"
      working-directory: './personal_genchatbotconnector' # This is the directory containing wrangler.toml